
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: python_app
    environment:
      - MONGO_PASSWORD:${MONGO_PASSWORD}
      - HOST:${HOST}
      - MONGO_USERNAME:${MONGO_USERNAME}
      - MONGO_PASSWORD:${MONGO_PASSWORD}
      - DB:${DB}
      - URI:${URI}
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
